### ISSUE TITLE
Truecaller Not working in group

### ISSUE THREAD

**Issue by ajitraj086** [jacktheboss220/WhatsAppBotMultiDevice#1]
![truecaller error](https://user-images.githubusercontent.com/25348958/197986310-b7f137b2-908c-4385-ad03-b559e4becb7d.PNG)

**Comment by jacktheboss220** [comment]
Fixed.
Go Check.  https://github.com/jacktheboss220/WhatsAppBotMultiDevice/commit/a85a8a8bd1e7dd18ea005d77306d772d1aaf7dc4
