### ISSUE TITLE
Hello idk much I have problem what docker project I add here

### ISSUE THREAD

**Issue by Mrunknow3** [jacktheboss220/WhatsAppBotMultiDevice#24]
![Screenshot_2024-03-17-20-15-05-982_com.mycompany.app.soulbrowser.jpg](https://github.com/jacktheboss220/WhatsAppBotMultiDevice/assets/154901963/3fc64ace-1693-4fe9-b77e-b81cf6c4c249)

**Comment by jacktheboss220** [comment]
use the github connect type.

**Comment by Mrunknow3** [comment]
You can explain some deep

**Comment by jacktheboss220** [comment]
like select the github option, and if you already forked this repo then connect it, koyeb will do the rest
